name: ontogent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=22.0.4
  - pip:
    - anthropic>=0.6.0
    - langchain>=0.0.267
    - pydantic>=2.0.0
    - pytest>=7.3.1
    - requests>=2.31.0
    - python-dotenv>=1.0.0
    - ruff>=0.0.278
    - black>=23.7.0 