name: UBERON Agent CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install Rye
      run: |
        curl -sSf https://rye-up.com/get | bash
        echo "Installation completed, checking results..."
        ls -la $HOME/.rye/bin || echo "Rye bin directory not found"
        
        # Add Rye to PATH and ensure it's executable
        if [ -f "$HOME/.rye/bin/rye" ]; then
          chmod +x $HOME/.rye/bin/rye
          echo "Rye found, making executable"
        fi
        
        # Source the shell profile if it exists
        if [ -f "$HOME/.profile" ]; then
          echo "Sourcing .profile"
          source $HOME/.profile
        fi
        
        # Add to GitHub PATH env var and current PATH
        echo "$HOME/.rye/bin" >> $GITHUB_PATH
        export PATH="$HOME/.rye/bin:$PATH"
        
        # Diagnostic info
        echo "Current PATH: $PATH"
        which rye || echo "Rye not in PATH"
        
        # Attempt direct execution
        $HOME/.rye/bin/rye --version || echo "Direct execution failed"
    
    - name: Install dependencies
      run: |
        export PATH="$HOME/.rye/bin:$PATH"
        echo "PATH: $PATH"
        $HOME/.rye/bin/rye sync
    
    - name: Lint with Ruff
      run: |
        export PATH="$HOME/.rye/bin:$PATH"
        $HOME/.rye/bin/rye run python -m ruff .
    
    - name: Test with pytest
      run: |
        export PATH="$HOME/.rye/bin:$PATH"
        $HOME/.rye/bin/rye run python -m pytest
      env:
        # Use dummy API key for tests (mocks will be used)
        ANTHROPIC_API_KEY: dummy_key_for_testing
    
    - name: Build package
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        export PATH="$HOME/.rye/bin:$PATH"
        $HOME/.rye/bin/rye build
    
    - name: Upload artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: dist/ 