name: UBERON Agent CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install Rye
      run: |
        echo "Installing Rye using pipx..."
        pipx install rye
        pipx ensurepath
        
        # Add to GitHub PATH env var and current PATH
        echo "$(pipx environment -v PIPX_BIN_DIR)" >> $GITHUB_PATH
        export PATH="$(pipx environment -v PIPX_BIN_DIR):$PATH"
        
        # Diagnostic info
        echo "Current PATH: $PATH"
        which rye || echo "Rye not in PATH"
        
        # Test rye
        rye --version
    
    - name: Initialize project
      run: |
        echo "Initializing Rye project..."
        cd $GITHUB_WORKSPACE
        ls -la
        
        # If pyproject.toml exists, we're in a Rye project
        if [ -f "pyproject.toml" ]; then
          echo "Found pyproject.toml, syncing dependencies..."
          rye sync
        else
          echo "No pyproject.toml found. Current directory:"
          ls -la
          echo "ERROR: This doesn't appear to be a Rye project"
          exit 1
        fi
    
    - name: Lint with Ruff
      run: |
        rye run python -m ruff .
    
    - name: Test with pytest
      run: |
        rye run python -m pytest
      env:
        # Use dummy API key for tests (mocks will be used)
        ANTHROPIC_API_KEY: dummy_key_for_testing
    
    - name: Build package
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        rye build
    
    - name: Upload artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: dist/ 